http {
	include mime.types;
	default_type text/html;

	# Backend
	server {
		listen 80;
		
		# Backend
		location /api/ {
			proxy_pass http://backend:8080/;
			
			types {
				application/javascript js;
			}
		}
		
		# Authentication
		location /auth/ {
			proxy_pass http://auth:8080/;
		}
		
		# Frontend
		location / {
			proxy_pass http://frontend:4200/;
		}
	}
}

events {}
