http {
	# Backend
	server {
		listen 80;
		
		# Backend
		location /api/ {
			proxy_pass http://backend:8080/;
		}
		
		# Authentication
		location /auth/ {
			proxy_pass http://auth:8080/;
		}
		
		# Frontend
		location /web/ {
			proxy_pass http://frontend:4200/;
		}
	}
}

events {}
